import { QwikIntrinsicElements } from "@builder.io/qwik";

export const CONTAINER_TAGS: (keyof QwikIntrinsicElements)[] = [
  "div",
  "section",
  "article",
  "aside",
  "nav",
  "header",
  "footer",
  "main",
  "ul",
  "ol",
  "li",
  "table",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "td",
  "th",
  "details",
  "summary",
  "fieldset",
  "legend",
  "form",
  "iframe",
  "figure",
  "figcaption",
  "dialog",
  "blockquote",
  "canvas",
  "template",
] as const;

export const TAG_NAMES: Required<{ [E in keyof QwikIntrinsicElements]: E }> = {
  a: "a",
  abbr: "abbr",
  address: "address",
  area: "area",
  article: "article",
  aside: "aside",
  audio: "audio",
  b: "b",
  base: "base",
  bdi: "bdi",
  bdo: "bdo",
  blockquote: "blockquote",
  body: "body",
  br: "br",
  button: "button",
  canvas: "canvas",
  caption: "caption",
  cite: "cite",
  code: "code",
  col: "col",
  colgroup: "colgroup",
  data: "data",
  datalist: "datalist",
  dd: "dd",
  del: "del",
  details: "details",
  dfn: "dfn",
  dialog: "dialog",
  div: "div",
  dl: "dl",
  dt: "dt",
  em: "em",
  embed: "embed",
  fieldset: "fieldset",
  figcaption: "figcaption",
  figure: "figure",
  footer: "footer",
  form: "form",
  h1: "h1",
  h2: "h2",
  h3: "h3",
  h4: "h4",
  h5: "h5",
  h6: "h6",
  head: "head",
  header: "header",
  hgroup: "hgroup",
  hr: "hr",
  html: "html",
  i: "i",
  iframe: "iframe",
  img: "img",
  input: "input",
  ins: "ins",
  kbd: "kbd",
  label: "label",
  legend: "legend",
  li: "li",
  link: "link",
  main: "main",
  map: "map",
  mark: "mark",
  menu: "menu",
  meta: "meta",
  meter: "meter",
  nav: "nav",
  noscript: "noscript",
  object: "object",
  ol: "ol",
  optgroup: "optgroup",
  option: "option",
  output: "output",
  p: "p",
  picture: "picture",
  pre: "pre",
  progress: "progress",
  q: "q",
  rp: "rp",
  rt: "rt",
  ruby: "ruby",
  s: "s",
  samp: "samp",
  script: "script",
  search: "search",
  section: "section",
  select: "select",
  slot: "slot",
  small: "small",
  source: "source",
  span: "span",
  strong: "strong",
  style: "style",
  sub: "sub",
  summary: "summary",
  sup: "sup",
  table: "table",
  tbody: "tbody",
  td: "td",
  template: "template",
  textarea: "textarea",
  tfoot: "tfoot",
  th: "th",
  thead: "thead",
  time: "time",
  title: "title",
  tr: "tr",
  track: "track",
  u: "u",
  ul: "ul",
  var: "var",
  video: "video",
  wbr: "wbr",
  symbol: "symbol",
  animate: "animate",
  animateMotion: "animateMotion",
  animateTransform: "animateTransform",
  circle: "circle",
  clipPath: "clipPath",
  defs: "defs",
  desc: "desc",
  ellipse: "ellipse",
  feBlend: "feBlend",
  feColorMatrix: "feColorMatrix",
  feComponentTransfer: "feComponentTransfer",
  feComposite: "feComposite",
  feConvolveMatrix: "feConvolveMatrix",
  feDiffuseLighting: "feDiffuseLighting",
  feDisplacementMap: "feDisplacementMap",
  feDistantLight: "feDistantLight",
  feDropShadow: "feDropShadow",
  feFlood: "feFlood",
  feFuncA: "feFuncA",
  feFuncB: "feFuncB",
  feFuncG: "feFuncG",
  feFuncR: "feFuncR",
  feGaussianBlur: "feGaussianBlur",
  feImage: "feImage",
  feMerge: "feMerge",
  feMergeNode: "feMergeNode",
  feMorphology: "feMorphology",
  feOffset: "feOffset",
  fePointLight: "fePointLight",
  feSpecularLighting: "feSpecularLighting",
  feSpotLight: "feSpotLight",
  feTile: "feTile",
  feTurbulence: "feTurbulence",
  filter: "filter",
  foreignObject: "foreignObject",
  g: "g",
  image: "image",
  line: "line",
  linearGradient: "linearGradient",
  marker: "marker",
  mask: "mask",
  metadata: "metadata",
  mpath: "mpath",
  path: "path",
  pattern: "pattern",
  polygon: "polygon",
  polyline: "polyline",
  radialGradient: "radialGradient",
  rect: "rect",
  set: "set",
  stop: "stop",
  svg: "svg",
  switch: "switch",
  text: "text",
  textPath: "textPath",
  tspan: "tspan",
  use: "use",
  view: "view",
};
